modLoader="javafml"
loaderVersion="[41,)" 
license="MIT License"
[[mods]]
modId="jak"
version="${file.jarVersion}"
displayName="JAK Minecraft Mod"
logoFile="logo.png"
credits="Thanks for this mod goes to JAK"
authors="JAK"
description='''
A Minecraft Mod made by JAK
'''
[[dependencies.jak]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.jak]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
